### ISSUE TITLE
unload command

### ISSUE THREAD

**Issue by loranger** [franzliedke/studio#67]
Hello (and thank you so much for this awesome composer enhancement),

I think we really miss an `unload` command which basically would reverse the `load` command without deleting the local repository:

When I update a project and its dependencies, I really do not want to delete the local depencency.
I would need it for other projects, or maybe to switch back to a specific branch, but `scrap` just remove everything.

I used to `rm studio.json` but when I load a few dependency locally, I have to re-load the ones I need to keep.

Maybe `unload` would parse the studio.json and remove the path line ?

**Comment by loranger** [comment]
Oups, sorry @rask 
I didn't realize you already made a PR :/

**Comment by rask** [comment]
I saw this issue and kinda jumped on it, didn't know you had something in the works too!

Seems like you have more time invested on this (with some better planning too from what I gathered from your PR), so maybe @franzliedke can pick your implementation instead of mine if he prefers so.

Anyways no harm done in my eyes there. :)

**Comment by loranger** [comment]
I'm glad you didn't take any offense.

No matter what PR @franzliedke will pick, the main thing is that we'll be able to unload local packages 😉

**Comment by rask** [comment]
Yeah, its a good feature to add. :+1:

**Comment by franzliedke** [comment]
Thanks, folks. This is now available in [version 0.11.1](https://github.com/franzliedke/studio/releases/tag/0.11.1).
